### ISSUE TITLE
HU02: Consultar la información detallada de un álbum

### ISSUE THREAD

**Issue by Julianrvillamil** [Julianrvillamil/AppVynils#3]
Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él.

**Comment by nicbot23** [comment]
## HU02 - Consultar la información detallada de un álbum
**Como usuario visitante quiero ver el detalle de un álbum para ampliar la información sobre él.**

### Tareas:
1. **Diseño UX/UI de la pantalla de detalles de álbum:**
   - Crear un wireframe de la pantalla que muestre los detalles del álbum.
   - Definir el layout en XML para mostrar la información detallada (nombre del álbum, artista, lista de canciones, fecha de lanzamiento, etc.).
   - Incluir el diseño de imágenes o carátulas del álbum en una vista ampliada.

2. **Implementación de la API REST (Backend):**
   - Implementar la llamada a la API para obtener la información detallada del álbum seleccionando un ID o referencia de álbum.
   - Definir un modelo de datos detallado para álbumes con los campos necesarios.
   - Manejar el estado de carga y errores en esta pantalla.

3. **Conexión de la navegación:**
   - Implementar la lógica para recibir el ID o referencia del álbum seleccionado desde la pantalla del catálogo.
   - Asegurarse de que la información en pantalla coincida con el álbum seleccionado previamente.

4. **Optimización para pantallas pequeñas:**
   - Ajustar el layout de la pantalla para que sea compatible con dispositivos móviles de diferentes tamaños (responsive design).

5. **Mockups**
  - Pantalla de mockup para consultar info detallada de album.
